spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/depot
        username: root
        password: 1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: libai.sm.bootbatis.model
    config-location: classpath:mappers/config/mybatis-config.xml # 注意：对应实体类的路径

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
logging:
  path: /spring/log
  level:
    libai.sm.bootbatis.dao: DEBUG

#日志